#!/usr/bin/env python3
"""CloudCompare PLY export with optional column-wise ground-bias compensation."""

from __future__ import annotations

import argparse
import sys
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd
import yaml

import reconstruct_ground_pointcloud_interactive as core


PLY_COLUMNS = ["Xg_mm", "Yg_mm", "Zg_mm", "u", "v"]


@dataclass(frozen=True)
class GroundBiasTable:
    path: Path
    columns: np.ndarray
    bias_mm: np.ndarray
    compensation_axis: str = "u"


@dataclass(frozen=True)
class V2Options:
    ground_bias_table_path: Path | None
    multi_obstacle_max_u_gap_px: float
    multi_obstacle_min_points: int | None


SEGMENT_COLUMNS = [
    "image",
    "segment_id",
    "point_count",
    "u_min",
    "u_max",
    "xg_min_mm",
    "xg_max_mm",
    "yg_min_mm",
    "yg_max_mm",
    "zg_min_mm",
    "zg_max_mm",
    "ground_baseline_zg_mm",
    "height_threshold_mm",
    "height_min_mm",
    "height_max_mm",
    "height_mean_mm",
    "height_median_mm",
    "height_std_mm",
    "line_centre_xg_mm",
    "line_centre_yg_mm",
    "line_direction_x",
    "line_direction_y",
    "line_fit_rmse_mm",
]


def _parse_v2_args(argv: list[str] | None) -> tuple[V2Options, list[str] | None]:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument(
        "--ground-bias-table",
        type=Path,
        default=None,
        help="ground_bias_table.npy generated by generate_ground_bias_compensation.py.",
    )
    parser.add_argument(
        "--multi-obstacle-max-u-gap",
        type=float,
        default=20.0,
        help="Split obstacle points into different objects when adjacent u gap is larger than this value.",
    )
    parser.add_argument(
        "--multi-obstacle-min-points",
        type=int,
        default=None,
        help="Minimum points per obstacle segment. Defaults to obstacle_fit.min_points from config.",
    )
    known, remaining = parser.parse_known_args(argv)
    ground_bias_table_path = (
        known.ground_bias_table.expanduser().resolve()
        if known.ground_bias_table is not None
        else None
    )
    options = V2Options(
        ground_bias_table_path=ground_bias_table_path,
        multi_obstacle_max_u_gap_px=known.multi_obstacle_max_u_gap,
        multi_obstacle_min_points=known.multi_obstacle_min_points,
    )
    return options, remaining


def load_ground_bias_table(path: Path) -> GroundBiasTable:
    if not path.is_file():
        raise core.ReconstructionError(f"Ground-bias table does not exist: {path}")
    try:
        payload = np.load(path, allow_pickle=True).item()
    except (OSError, ValueError, AttributeError) as exc:
        raise core.ReconstructionError(f"Cannot load ground-bias table: {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise core.ReconstructionError(f"Ground-bias table must be a dict: {path}")
    missing = [name for name in ("columns", "bias_mm") if name not in payload]
    if missing:
        raise core.ReconstructionError(
            f"Ground-bias table is missing fields: {', '.join(missing)}"
        )

    columns = np.asarray(payload["columns"], dtype=np.float64).reshape(-1)
    bias_mm = np.asarray(payload["bias_mm"], dtype=np.float64).reshape(-1)
    if columns.size == 0:
        raise core.ReconstructionError("Ground-bias table has no columns")
    if columns.shape != bias_mm.shape:
        raise core.ReconstructionError(
            f"Ground-bias table shape mismatch: columns={columns.shape}, bias={bias_mm.shape}"
        )
    if not (np.isfinite(columns).all() and np.isfinite(bias_mm).all()):
        raise core.ReconstructionError("Ground-bias table contains NaN or Inf")

    order = np.argsort(columns)
    columns = columns[order]
    bias_mm = bias_mm[order]
    if np.any(np.diff(columns) <= 0.0):
        raise core.ReconstructionError("Ground-bias table columns must be unique")
    metadata = payload.get("metadata", {})
    axis = payload.get("compensation_axis")
    if axis is None and isinstance(metadata, dict):
        axis = metadata.get("compensation_axis")
    compensation_axis = "u" if axis is None else str(axis).strip().lower()
    if compensation_axis not in {"u", "v"}:
        raise core.ReconstructionError(
            f"Ground-bias table has invalid compensation_axis: {axis!r}"
        )
    return GroundBiasTable(
        path=path,
        columns=columns,
        bias_mm=bias_mm,
        compensation_axis=compensation_axis,
    )


def apply_ground_bias_compensation(
    frame: pd.DataFrame, table: GroundBiasTable
) -> pd.DataFrame:
    coordinate_name = table.compensation_axis
    missing = [
        column for column in (coordinate_name, "Zg_mm") if column not in frame.columns
    ]
    if missing:
        raise core.ReconstructionError(
            f"Ground-bias compensation is missing columns: {', '.join(missing)}"
        )
    compensated = frame.copy()
    if compensated.empty:
        compensated["Zg_raw_mm"] = np.asarray([], dtype=np.float64)
        compensated["ground_bias_mm"] = np.asarray([], dtype=np.float64)
        return compensated

    coordinate = compensated[coordinate_name].to_numpy(dtype=np.float64)
    z_raw = compensated["Zg_mm"].to_numpy(dtype=np.float64)
    outside = (coordinate < table.columns[0]) | (coordinate > table.columns[-1])
    if np.any(outside):
        warnings.warn(
            f"{np.count_nonzero(outside)} point(s) are outside the ground-bias "
            f"{coordinate_name} range [{table.columns[0]:g}, {table.columns[-1]:g}] px; "
            "using the nearest endpoint bias",
            RuntimeWarning,
            stacklevel=2,
        )
    point_bias = np.interp(
        coordinate,
        table.columns,
        table.bias_mm,
        left=table.bias_mm[0],
        right=table.bias_mm[-1],
    )
    compensated["Zg_raw_mm"] = z_raw
    compensated["ground_bias_mm"] = point_bias
    compensated["Zg_mm"] = z_raw - point_bias
    return compensated


def _height_context(
    frame: pd.DataFrame, params: core.ObstacleFitParams
) -> dict[str, Any]:
    if frame.empty or len(frame) < params.min_points:
        mask = np.zeros(len(frame), dtype=bool)
        return {
            "valid": False,
            "reason": "not enough valid points",
            "ground_baseline_zg_mm": None,
            "ground_noise_sigma_mm": None,
            "height_threshold_mm": None,
            "height_mm": np.asarray([], dtype=np.float64),
            "obstacle_mask": mask,
        }
    zg = frame["Zg_mm"].to_numpy(dtype=np.float64)
    ground_limit = float(np.quantile(zg, params.ground_quantile))
    ground_samples = zg[zg <= ground_limit]
    ground_baseline = float(np.median(ground_samples))
    ground_sigma = 1.4826 * float(
        np.median(np.abs(ground_samples - ground_baseline))
    )
    height_threshold = max(
        params.min_height_mm,
        params.noise_sigma_multiplier * ground_sigma,
    )
    height_mm = zg - ground_baseline
    obstacle_mask = height_mm >= height_threshold
    return {
        "valid": True,
        "reason": None,
        "ground_baseline_zg_mm": ground_baseline,
        "ground_noise_sigma_mm": ground_sigma,
        "height_threshold_mm": float(height_threshold),
        "height_mm": height_mm,
        "obstacle_mask": obstacle_mask,
    }


def disabled_single_obstacle_fit(
    frame: pd.DataFrame, params: core.ObstacleFitParams
) -> dict[str, Any]:
    context = _height_context(frame, params)
    return {
        "found": False,
        "reason": "single-obstacle height is disabled in v2; see obstacle_segments.csv",
        "obstacle_point_count": int(np.count_nonzero(context["obstacle_mask"])),
        "ground_baseline_zg_mm": context["ground_baseline_zg_mm"],
        "ground_noise_sigma_mm": context["ground_noise_sigma_mm"],
        "height_threshold_mm": context["height_threshold_mm"],
        "obstacle_mask": context["obstacle_mask"],
    }


def _fit_xy_line(points_xy: np.ndarray) -> dict[str, Any]:
    if len(points_xy) < 2:
        return {
            "line_centre_xg_mm": None,
            "line_centre_yg_mm": None,
            "line_direction_x": None,
            "line_direction_y": None,
            "line_fit_rmse_mm": None,
            "_line_endpoints_xy": None,
        }
    centre = np.mean(points_xy, axis=0)
    _, _, right_vectors = np.linalg.svd(points_xy - centre, full_matrices=False)
    direction = right_vectors[0]
    if direction[0] < 0.0:
        direction = -direction
    projections = (points_xy - centre) @ direction
    fitted_xy = centre + projections[:, None] * direction
    residuals = np.linalg.norm(points_xy - fitted_xy, axis=1)
    endpoints = np.vstack(
        [
            centre + float(np.min(projections)) * direction,
            centre + float(np.max(projections)) * direction,
        ]
    )
    return {
        "line_centre_xg_mm": float(centre[0]),
        "line_centre_yg_mm": float(centre[1]),
        "line_direction_x": float(direction[0]),
        "line_direction_y": float(direction[1]),
        "line_fit_rmse_mm": float(np.sqrt(np.mean(residuals**2))),
        "_line_endpoints_xy": endpoints,
    }


def detect_obstacle_segments(
    frame: pd.DataFrame,
    params: core.ObstacleFitParams,
    max_u_gap_px: float,
    min_segment_points: int | None,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if max_u_gap_px <= 0.0:
        raise core.ReconstructionError("--multi-obstacle-max-u-gap must be > 0")
    segment_min_points = params.min_points if min_segment_points is None else min_segment_points
    if segment_min_points <= 0:
        raise core.ReconstructionError("--multi-obstacle-min-points must be > 0")

    context = _height_context(frame, params)
    mask = np.asarray(context["obstacle_mask"], dtype=bool)
    if not bool(context["valid"]) or not np.any(mask):
        summary = {
            "segment_count": 0,
            "candidate_point_count": int(np.count_nonzero(mask)),
            "ground_baseline_zg_mm": context["ground_baseline_zg_mm"],
            "ground_noise_sigma_mm": context["ground_noise_sigma_mm"],
            "height_threshold_mm": context["height_threshold_mm"],
            "max_u_gap_px": max_u_gap_px,
            "min_segment_points": int(segment_min_points),
        }
        return [], summary

    high = frame.loc[mask].copy()
    high["_height_mm"] = context["height_mm"][mask]
    high["_source_index"] = high.index.to_numpy()
    high = high.sort_values("u", kind="mergesort").reset_index(drop=True)
    u_values = high["u"].to_numpy(dtype=np.float64)
    gaps = np.diff(u_values)
    split_after = np.where(gaps > max_u_gap_px)[0]
    starts = np.r_[0, split_after + 1]
    ends = np.r_[split_after, len(high) - 1]

    rows: list[dict[str, Any]] = []
    for start, end in zip(starts, ends):
        segment = high.iloc[start : end + 1]
        if len(segment) < segment_min_points:
            continue
        heights = segment["_height_mm"].to_numpy(dtype=np.float64)
        xy = segment[["Xg_mm", "Yg_mm"]].to_numpy(dtype=np.float64)
        line = _fit_xy_line(xy)
        row = {
            "segment_id": len(rows) + 1,
            "point_count": int(len(segment)),
            "u_min": float(segment["u"].min()),
            "u_max": float(segment["u"].max()),
            "xg_min_mm": float(segment["Xg_mm"].min()),
            "xg_max_mm": float(segment["Xg_mm"].max()),
            "yg_min_mm": float(segment["Yg_mm"].min()),
            "yg_max_mm": float(segment["Yg_mm"].max()),
            "zg_min_mm": float(segment["Zg_mm"].min()),
            "zg_max_mm": float(segment["Zg_mm"].max()),
            "ground_baseline_zg_mm": context["ground_baseline_zg_mm"],
            "height_threshold_mm": context["height_threshold_mm"],
            "height_min_mm": float(np.min(heights)),
            "height_max_mm": float(np.max(heights)),
            "height_mean_mm": float(np.mean(heights)),
            "height_median_mm": float(np.median(heights)),
            "height_std_mm": float(np.std(heights)),
            "_indices": segment["_source_index"].to_numpy(dtype=int),
            **line,
        }
        rows.append(row)

    summary = {
        "segment_count": int(len(rows)),
        "candidate_point_count": int(len(high)),
        "ground_baseline_zg_mm": context["ground_baseline_zg_mm"],
        "ground_noise_sigma_mm": context["ground_noise_sigma_mm"],
        "height_threshold_mm": context["height_threshold_mm"],
        "max_u_gap_px": max_u_gap_px,
        "min_segment_points": int(segment_min_points),
    }
    return rows, summary


def _public_segment_row(row: dict[str, Any], image_name: str | None = None) -> dict[str, Any]:
    payload = {key: row.get(key) for key in SEGMENT_COLUMNS if key != "image"}
    if image_name is not None:
        payload = {"image": image_name, **payload}
    return payload


def save_obstacle_segments_csv(
    rows: list[dict[str, Any]],
    path: Path,
    image_name: str | None = None,
) -> None:
    include_image = image_name is not None or any("image" in row for row in rows)
    if rows:
        data = [
            _public_segment_row(
                row,
                image_name if image_name is not None else row.get("image"),
            )
            for row in rows
        ]
        columns = SEGMENT_COLUMNS if include_image else SEGMENT_COLUMNS[1:]
        pd.DataFrame(data, columns=columns).to_csv(path, index=False, encoding="utf-8-sig")
    else:
        columns = SEGMENT_COLUMNS if include_image else SEGMENT_COLUMNS[1:]
        pd.DataFrame(columns=columns).to_csv(path, index=False, encoding="utf-8-sig")


def save_obstacle_segments_plot(
    frame: pd.DataFrame,
    rows: list[dict[str, Any]],
    path: Path,
    title: str,
    image_aspect_ratio: float,
) -> None:
    plt = core.plt
    figure, axis = plt.subplots(figsize=(10, 8))
    if frame.empty:
        axis.text(0.5, 0.5, "No valid points", transform=axis.transAxes, ha="center")
    else:
        axis.scatter(frame["Xg_mm"], frame["Yg_mm"], c="#aeb6bf", s=5, label="All points")
        colors = plt.get_cmap("tab10")
        notes: list[str] = []
        for row in rows:
            segment = frame.loc[np.asarray(row["_indices"], dtype=int)]
            color = colors((int(row["segment_id"]) - 1) % 10)
            axis.scatter(
                segment["Xg_mm"],
                segment["Yg_mm"],
                color=color,
                s=12,
                label=f"Segment {row['segment_id']}",
            )
            endpoints = row.get("_line_endpoints_xy")
            if endpoints is not None:
                endpoints = np.asarray(endpoints, dtype=np.float64)
                axis.plot(endpoints[:, 0], endpoints[:, 1], color=color, linewidth=2.0)
            notes.append(
                f"S{row['segment_id']}: median={row['height_median_mm']:.2f} mm, "
                f"mean={row['height_mean_mm']:.2f} mm, n={row['point_count']}"
            )
        if not notes:
            notes.append("No obstacle segment found")
        axis.text(
            0.02,
            0.98,
            "\n".join(notes[:8]),
            transform=axis.transAxes,
            va="top",
            ha="left",
            bbox={"boxstyle": "round", "facecolor": "white", "alpha": 0.88},
        )
        x0, x1, y0, y1 = core.calculate_top_view_limits(
            frame["Xg_mm"].to_numpy(dtype=np.float64),
            frame["Yg_mm"].to_numpy(dtype=np.float64),
            image_aspect_ratio,
        )
        axis.set_xlim(x0, x1)
        axis.set_ylim(y0, y1)
        axis.legend(loc="lower right")
    axis.set_xlabel("Xg (mm)")
    axis.set_ylabel("Yg (mm)")
    axis.set_title(f"Obstacle segments | {title}")
    axis.set_aspect("equal", adjustable="box")
    axis.grid(True, linestyle="--", alpha=0.35)
    figure.tight_layout()
    figure.savefig(path, dpi=170)
    plt.close(figure)


def _make_compensated_reconstruct_points(
    original_reconstruct_points: Callable[..., tuple[pd.DataFrame, dict[str, int]]],
    table: GroundBiasTable,
) -> Callable[..., tuple[pd.DataFrame, dict[str, int]]]:
    def reconstruct_points_with_compensation(
        pixels_uv: np.ndarray,
        calibration: core.Calibration,
        params: core.ReconstructionParams,
    ) -> tuple[pd.DataFrame, dict[str, int]]:
        frame, filtered = original_reconstruct_points(pixels_uv, calibration, params)
        return apply_ground_bias_compensation(frame, table), filtered

    return reconstruct_points_with_compensation


def save_ground_pointcloud_ply(frame: pd.DataFrame, path: Path) -> None:
    """Save ground-frame points as ASCII PLY. Coordinates are millimetres."""
    missing = [column for column in PLY_COLUMNS if column not in frame.columns]
    if missing:
        raise core.ReconstructionError(
            f"PLY export is missing columns: {', '.join(missing)}"
        )

    values = frame[PLY_COLUMNS].to_numpy(dtype=np.float64)
    if not np.isfinite(values).all():
        raise core.ReconstructionError("PLY export data contains NaN or Inf")

    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "ply",
        "format ascii 1.0",
        "comment coordinate_system ground",
        "comment units millimeter",
        "comment single_frame_laser_profile_no_surface_interpolation",
        "comment z_is_ground_bias_compensated_if_ground_bias_table_was_provided",
        f"element vertex {len(values)}",
        "property double x",
        "property double y",
        "property double z",
        "property double u",
        "property double v",
        "property double height_mm",
        "end_header",
    ]
    try:
        with path.open("w", encoding="ascii", newline="\n") as stream:
            stream.write("\n".join(header) + "\n")
            for xg, yg, zg, u, v in values:
                stream.write(
                    f"{xg:.9f} {yg:.9f} {zg:.9f} "
                    f"{u:.9f} {v:.9f} {zg:.9f}\n"
                )
    except OSError as exc:
        raise core.ReconstructionError(f"Cannot write PLY point cloud: {path}: {exc}") from exc


def _bias_summary(frame: pd.DataFrame, table: GroundBiasTable | None) -> dict[str, Any]:
    if table is None:
        return {
            "applied": False,
            "table": None,
        }
    if "ground_bias_mm" not in frame.columns or frame.empty:
        return {
            "applied": True,
            "table": str(table.path),
            "point_count": int(len(frame)),
            "bias_min_mm": None,
            "bias_max_mm": None,
            "bias_mean_mm": None,
        }
    bias = frame["ground_bias_mm"].to_numpy(dtype=np.float64)
    return {
        "applied": True,
        "table": str(table.path),
        "point_count": int(len(frame)),
        "bias_min_mm": float(np.min(bias)),
        "bias_max_mm": float(np.max(bias)),
        "bias_mean_mm": float(np.mean(bias)),
    }


def _append_metadata(
    statistics_path: Path,
    point_count: int,
    table: GroundBiasTable | None,
    frame: pd.DataFrame,
    segment_summary: dict[str, Any],
) -> None:
    try:
        with statistics_path.open("r", encoding="utf-8") as stream:
            statistics = yaml.safe_load(stream)
        if not isinstance(statistics, dict):
            raise core.ReconstructionError(f"Invalid statistics file: {statistics_path}")
        statistics["ground_pointcloud_export"] = {
            "file": "points_ground.ply",
            "format": "PLY ASCII 1.0",
            "coordinate_system": "ground",
            "coordinate_unit": "mm",
            "point_count": point_count,
            "surface_interpolation": False,
        }
        statistics["ground_bias_compensation"] = _bias_summary(frame, table)
        statistics["multi_obstacle_detection"] = {
            "single_obstacle_fit_disabled": True,
            "segments_file": "obstacle_segments.csv",
            "segments_plot": "obstacle_segments.png",
            **segment_summary,
        }
        with statistics_path.open("w", encoding="utf-8") as stream:
            yaml.safe_dump(statistics, stream, allow_unicode=True, sort_keys=False)
    except OSError as exc:
        raise core.ReconstructionError(
            f"Cannot update point-cloud export metadata: {statistics_path}: {exc}"
        ) from exc


def _make_cloudcompare_process_frame(
    original_process_frame: Callable[..., dict[str, Any]],
    table: GroundBiasTable | None,
    options: V2Options,
    summary_rows: list[dict[str, Any]],
    output_dirs: list[Path],
) -> Callable[..., dict[str, Any]]:
    def process_frame_with_ply(
        image_path: Path,
        output_dir: Path,
        calibration: core.Calibration,
        extraction: core.ExtractionParams,
        reconstruction: core.ReconstructionParams,
        obstacle_fit_params: core.ObstacleFitParams,
        show_3d: bool,
    ) -> dict[str, Any]:
        statistics = original_process_frame(
            image_path,
            output_dir,
            calibration,
            extraction,
            reconstruction,
            obstacle_fit_params,
            show_3d,
        )
        frame_dir = output_dir / image_path.stem
        if not output_dirs:
            output_dirs.append(output_dir)
        csv_path = frame_dir / "points_ground.csv"
        try:
            frame = pd.read_csv(csv_path)
        except (OSError, pd.errors.ParserError, UnicodeError) as exc:
            raise core.ReconstructionError(
                f"Cannot read reconstructed ground CSV for PLY export: {csv_path}: {exc}"
            ) from exc

        if len(frame) != statistics["valid_point_count"]:
            raise core.ReconstructionError(
                "Point count check failed before PLY export: "
                f"CSV={len(frame)}, valid_point_count={statistics['valid_point_count']}"
            )
        segment_rows, segment_summary = detect_obstacle_segments(
            frame,
            obstacle_fit_params,
            options.multi_obstacle_max_u_gap_px,
            options.multi_obstacle_min_points,
        )
        save_obstacle_segments_csv(segment_rows, frame_dir / "obstacle_segments.csv")
        gray = core.read_mono8(image_path)
        save_obstacle_segments_plot(
            frame,
            segment_rows,
            frame_dir / "obstacle_segments.png",
            image_path.name,
            image_aspect_ratio=gray.shape[1] / gray.shape[0],
        )
        for row in segment_rows:
            summary_rows.append(_public_segment_row(row, image_path.name))

        save_ground_pointcloud_ply(frame, frame_dir / "points_ground.ply")
        _append_metadata(
            frame_dir / "statistics.yaml",
            len(frame),
            table,
            frame,
            segment_summary,
        )
        statistics["ground_pointcloud_file"] = "points_ground.ply"
        statistics["ground_pointcloud_point_count"] = len(frame)
        statistics["obstacle_mean_height_mm"] = None
        statistics["obstacle_line_fit_rmse_mm"] = None
        statistics["single_obstacle_fit_disabled"] = True
        statistics["obstacle_segments_file"] = "obstacle_segments.csv"
        statistics["obstacle_segments_plot"] = "obstacle_segments.png"
        statistics["obstacle_segment_count"] = segment_summary["segment_count"]
        statistics["obstacle_candidate_point_count"] = segment_summary["candidate_point_count"]
        statistics["obstacle_ground_baseline_zg_mm"] = segment_summary["ground_baseline_zg_mm"]
        statistics["obstacle_height_threshold_mm"] = segment_summary["height_threshold_mm"]
        for row in segment_rows[:6]:
            prefix = f"obstacle_segment_{row['segment_id']}"
            statistics[f"{prefix}_point_count"] = row["point_count"]
            statistics[f"{prefix}_height_mean_mm"] = row["height_mean_mm"]
            statistics[f"{prefix}_height_median_mm"] = row["height_median_mm"]
            statistics[f"{prefix}_u_min"] = row["u_min"]
            statistics[f"{prefix}_u_max"] = row["u_max"]
        bias_meta = _bias_summary(frame, table)
        statistics["ground_bias_compensation_applied"] = bias_meta["applied"]
        statistics["ground_bias_table"] = bias_meta["table"]
        statistics["ground_bias_min_mm"] = bias_meta.get("bias_min_mm")
        statistics["ground_bias_max_mm"] = bias_meta.get("bias_max_mm")
        statistics["ground_bias_mean_mm"] = bias_meta.get("bias_mean_mm")
        return statistics

    return process_frame_with_ply


def main(argv: list[str] | None = None) -> int:
    """Reuse the verified reconstruction entry point and add compensated PLY export."""
    raw_argv = sys.argv[1:] if argv is None else argv
    options, core_argv = _parse_v2_args(raw_argv)
    table = (
        load_ground_bias_table(options.ground_bias_table_path)
        if options.ground_bias_table_path
        else None
    )
    help_requested = any(item in ("-h", "--help") for item in raw_argv)
    if options.multi_obstacle_max_u_gap_px <= 0.0:
        raise core.ReconstructionError("--multi-obstacle-max-u-gap must be > 0")
    if options.multi_obstacle_min_points is not None and options.multi_obstacle_min_points <= 0:
        raise core.ReconstructionError("--multi-obstacle-min-points must be > 0")

    original_reconstruct_points = core.reconstruct_points
    original_process_frame = core.process_frame
    original_fit_obstacle_line = core.fit_obstacle_line
    summary_rows: list[dict[str, Any]] = []
    output_dirs: list[Path] = []
    if table is not None:
        core.reconstruct_points = _make_compensated_reconstruct_points(
            original_reconstruct_points, table
        )
    core.fit_obstacle_line = disabled_single_obstacle_fit
    core.process_frame = _make_cloudcompare_process_frame(
        original_process_frame,
        table,
        options,
        summary_rows,
        output_dirs,
    )
    try:
        if not help_requested:
            if table is None:
                print("Ground-bias compensation: disabled (--ground-bias-table not provided)")
            else:
                print(f"Ground-bias compensation: {table.path}")
            print(
                "Single-obstacle height: disabled; writing multi-obstacle segments instead"
            )
        result = core.main(core_argv)
        if output_dirs:
            save_obstacle_segments_csv(
                summary_rows,
                output_dirs[0] / "obstacle_segments_summary.csv",
            )
        return result
    finally:
        core.reconstruct_points = original_reconstruct_points
        core.fit_obstacle_line = original_fit_obstacle_line
        core.process_frame = original_process_frame


if __name__ == "__main__":
    raise SystemExit(main())
